additionalRepositories:
    - url: https://github.com/mohamedhajbi/backnest.git
      # checkoutLocation is relative to /workspaces
      checkoutLocation: backend

tasks:
  - name: frontend
    init: npm install 
    command: 
      docker-compose -f docker-compose.yml build;
      docker-compose -f docker-compose.yml up -d;
      docker-compose -f docker-compose.yml logs -f;

  - name: backend
    command:
      cd ../backend;
      npm i;
      npm i -g @nestjs/cli;
      docker-compose -f docker-compose.yml build;
      docker-compose -f docker-compose.yml up -d;
      docker-compose -f docker-compose.yml logs -f;


